version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py
  # Optional: build additional formats
  # formats:
  #   - pdf
  #   - epub

python:
  install:
    # 1) Install your project so autodoc can import it
    - method: pip
      path: .
    # 2) Install docs dependencies
    - requirements: docs/requirements.txt