version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Fail fast on syntax errors, then generate API stubs and show what's created
      - python -m compileall finmlkit
      - sphinx-apidoc -o docs/source/api finmlkit -f -e --module-first
      - ls -la docs/source/api

sphinx:
  configuration: docs/source/conf.py
  # Optional: uncomment to fail on warnings (useful once things are stable)
  fail_on_warning: false

python:
  install:
    # 1) Docs deps first
    - requirements: docs/requirements.txt
    # 2) Then your package (so autodoc can import it)
    - method: pip
      path: .