name: Bug report
description: Report a reproducible problem or regression
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue. Please provide as much detail as possible.
  - type: input
    id: summary
    attributes:
      label: Short summary
      placeholder: Briefly describe the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the exact steps to reproduce the behaviour
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: FinMLKit version
      placeholder: e.g. 0.1.10
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any error messages or stack traces
      render: shell
