name: Publish to PyPI on release tag

on:
  push:
    tags:
      - "v*.*.*"   # only semantic version tags

jobs:
  build-and-publish:
    permissions:
      id-token: write   # required for OIDC
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build sdist & wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          # No token needed with Trusted Publishing
          skip-existing: true
