name: Publish to PyPI on release tag

on:
  push:
    tags:
      - "v*.*.*"   # only semantic version tags

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # OIDC for Trusted Publishing
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install build tooling
        run: python -m pip install --upgrade pip setuptools wheel build twine

      - name: Clean previous builds
        run: rm -rf dist build *.egg-info

      - name: Build sdist & wheel (PEP 517)
        run: python -m build --sdist --wheel

      - name: Verify wheel METADATA
        run: |
          ls -lh dist
          python - <<'PY'
          import glob, zipfile, sys
          ok=True
          for fn in glob.glob('dist/*.whl'):
              with zipfile.ZipFile(fn) as z:
                  metas=[n for n in z.namelist() if n.endswith('.dist-info/METADATA')]
                  print("Wheel:", fn, "METADATA files:", metas)
                  if not metas: ok=False; continue
                  meta=z.read(metas[0]).decode('utf-8','ignore')
                  for k in ("Metadata-Version","Name","Version"):
                      line=next((l for l in meta.splitlines() if l.startswith(k+":")), None)
                      print(line or f"!! Missing {k}"); ok &= bool(line)
          sys.exit(0 if ok else 1)
          PY

      - name: Twine check
        run: python -m twine check dist/*

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@v1
        with:
          skip-existing: true
