# .github/workflows/release.yml
name: Release

on:
  push:
    tags: ['v*']          # runs only on version tags

permissions:
  contents: write         # release assets
  models:   read          # call GitHub Models inference API

jobs:
  release:
    runs-on: ubuntu-24.04 # explicit to avoid silent image switch

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # Fast, pre-built changelog generator
      - uses: orhun/git-cliff-action@v4        # pin major/minor or SHA
        id: cliff
        with:
          args: --tag ${{ github.ref_name }}
        env:
          OUTPUT: CHANGELOG.md             # action writes this file

      # Call GPT-5 via GitHub Models
      - name: Summarise with GPT-5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl "https://models.github.ai/inference/chat/completions" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -d @- <<'JSON' > SUMMARY.md
          {
            "model": "openai/gpt-5",
            "messages": [
              { "role": "system",
                "content": "You are a release-notes generator." },
              { "role": "user",
                "content": "$(cat CHANGELOG.md)" }
            ]
          }
          JSON

      # Publish the release
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name:     ${{ github.ref_name }}
          body_path: SUMMARY.md
          files: |
            CHANGELOG.md